### ISSUE TITLE
'k!promote' appears to be not working

### ISSUE THREAD

**Issue by ghost** [DiscordMusicBot/MusicBot#15]
```
121354117015666693/Tim#8397: k!promote
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 3670, in on_message
    response = await handler(**handler_kwargs)
  File "/usr/src/musicbot/musicbot/bot.py", line 3095, in cmd_promote
    btext = entry.title
AttributeError: 'coroutine' object has no attribute 'title'

```

**Comment by TBK** [comment]
I have pushed a commit that should fix it.
